server:
  servlet:
    context-path: /keepReport
  port: 8888

spring:
  thymeleaf:
    cache: false

  web:
    resources:
      static-locations: classpath:/static

  mvc:
    static-path-pattern: /static/**
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    connect-timeout: 300000

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

keepReport:
  # 设计首页地址路径
  indexPath: /keepReport
  # 是否开启文件储存系统
  enableFileProvider: true
  # 保存报表文件文件夹
  fileStoreDir: keep-report-files
  # 是否使用redis作为缓存
  enableRedis: false
  # redis缓存过期时间 (单位：分钟) 默认60分钟
  cacheExpire: 60
  # 是否开启云储存系统
  ossEnable: false
  # 云储存配置
  oss:
    # 端点，上传地址
    endpoint:
    # 云储存key
    access-key:
    # 云储存密钥
    secret-key:
    # 桶名称
    bucket-name:
    # 地区（可填可不填）
    region:
    # 最大连接时间
    max-connections: 100
    # 云储存上传路径
    prefix: source/report/

# 日志管理
logging:
  level:
    com:
      march:
        report: debug